#!/usr/bin/env python3
"""Submit optimized GPU relaxation jobs for all entangled packings in a directory.

Usage:
    python submit_batch_relax_gpu.py --base-dir results/2026-03-01_BATCH_...
"""

import argparse
import datetime
import os
import shutil
import subprocess
from pathlib import Path

REPO_DIR = Path(__file__).resolve().parent
RUNS_DIR = REPO_DIR / "runs"
RUNS_DIR.mkdir(exist_ok=True)

FILES_TO_COPY = [
    "batch_relax_gpu.py",
    "protocols.py",
    "optimization.py",
    "potentials.py",
    "transforms.py",
    "utils.py",
    "visualizations.py",
]

def parse_args():
    p = argparse.ArgumentParser(description="Submit Optimized GPU Relaxation Jobs")
    p.add_argument("--base-dir", type=str, required=True, 
                   help="Directory to search for q_entangled.npy files")
    p.add_argument("--AR-list", type=str, default="1000,500,300,100,50,25,10")
    p.add_argument("--Nmax", type=int, default=1000000)
    p.add_argument("--atol", type=float, default=1e-6)
    p.add_argument("--relax-dt", type=float, default=0.01)
    p.add_argument("--clearance", type=float, default=1.005)
    p.add_argument("--amp", type=float, default=100.0)

    # SLURM
    p.add_argument("--partition", type=str, default="gpu_test")
    p.add_argument("--time", type=str, default="0-12:00")
    p.add_argument("--mem", type=str, default="16000")
    p.add_argument("--gres", type=str, default="gpu:1")
    p.add_argument("--cuda-module", type=str, default="cuda/12.9")
    p.add_argument("--mail-user", type=str, default="jung@seas.harvard.edu")

    p.add_argument("--dry-run", action="store_true")
    p.add_argument("--force", action="store_true")
    return p.parse_args()

def generate_sbatch(args, run_py_name):
    return f"""#!/bin/bash
#SBATCH -n 1
#SBATCH -c 1
#SBATCH -N 1
#SBATCH -t {args.time}
#SBATCH -p {args.partition}
#SBATCH --mem={args.mem}
#SBATCH --gres={args.gres}
#SBATCH -o output_%j.out
#SBATCH -e errors_%j.err
#SBATCH --mail-type=END
#SBATCH --mail-user={args.mail_user}

module load {args.cuda_module}
module load python
mamba activate simdata-analysis

python {run_py_name}
"""

def main():
    args = parse_args()
    base_search_dir = Path(args.base_dir).resolve()
    
    # 1. Recursive search for q_entangled.npy
    print(f"Searching for entangled packings in {base_search_dir}...")
    target_dirs = []
    for root, dirs, files in os.walk(base_search_dir):
        if "q_entangled.npy" in files:
            target_dirs.append(Path(root))
            
    if not target_dirs:
        print("No q_entangled.npy files found.")
        return
        
    print(f"Found {len(target_dirs)} packings to relax.")

    timestamp = datetime.datetime.now().strftime("%Y%m%d-%H%M")

    for source_dir in target_dirs:
        # Create a unique run directory in REPO_DIR/runs
        source_rel = source_dir.relative_to(base_search_dir) if source_dir != base_search_dir else Path(source_dir.name)
        # Flatten the relative path for the run folder name
        safe_name = str(source_rel).replace("/", "_")
        run_name = f"{timestamp}_RELAX_{safe_name}"
        run_dir = RUNS_DIR / run_name
        
        if run_dir.exists() and not args.force:
            print(f"Skipping {run_name} (already exists). Use --force to overwrite.")
            continue
            
        run_dir.mkdir(parents=True, exist_ok=True)
        print(f"\nPreparing job in: {run_dir}")
        print(f"  Source: {source_dir}")

        # 1. Log provenance
        (run_dir / "source_info.log").write_text(f"Source: {source_dir}\nCreated: {datetime.datetime.now()}\n")

        # 2. Copy data files
        shutil.copy(source_dir / "q_entangled.npy", run_dir / "q_entangled.npy")
        if (source_dir / "x_entangled.txt").exists():
            shutil.copy(source_dir / "x_entangled.txt", run_dir / "x_entangled.txt")
        elif (source_dir.parent / "x_entangled.txt").exists():
            shutil.copy(source_dir.parent / "x_entangled.txt", run_dir / "x_entangled.txt")

        # 3. Copy necessary scripts from REPO_DIR
        for f in FILES_TO_COPY:
            shutil.copy(REPO_DIR / f, run_dir / f)
            
        # 4. Write runner script within the run_dir
        run_py_name = "run_optimized_relax.py"
        run_py_content = f"""import subprocess, sys
# This file was auto-generated by submit_batch_relax_gpu.py
cmd = [
    sys.executable, 'batch_relax_gpu.py', 'q_entangled.npy',
    '--AR-list', '{args.AR_list}',
    '--Nmax', '{args.Nmax}',
    '--atol', '{args.atol}',
    '--dt', '{args.relax_dt}',
    '--clearance', '{args.clearance}',
    '--amp', '{args.amp}'
]
"""
        if args.force:
            run_py_content += "cmd.append('--force')\n"
        run_py_content += "print('Executing:', ' '.join(cmd))\nsubprocess.check_call(cmd)\n"
        (run_dir / run_py_name).write_text(run_py_content)
        
        # 5. Write SBATCH script within the run_dir
        sbatch_txt = generate_sbatch(args, run_py_name)
        (run_dir / "Sbatch_relax.sh").write_text(sbatch_txt)
        
        # 6. Submit the job
        if not args.dry_run:
            print(f"Submitting job from {run_dir}...")
            # Use subprocess to run sbatch inside the run_dir
            try:
                subprocess.run(["sbatch", "Sbatch_relax.sh"], cwd=run_dir, check=True)
            except subprocess.CalledProcessError as e:
                print(f"Error submitting job: {e}")
        else:
            print(f"Dry run: folder prepared at {run_dir}")

    print("\nSubmission complete.")

if __name__ == "__main__":
    main()
